### ISSUE TITLE
More gracefully handle errors from fetching package download stats (e.g. package doesn't exist)

### ISSUE THREAD

**Issue by devjmetivier** [cheapsteak/npmcharts.com#146]
### The Problem

https://npmcharts.com/compare/@hookit/local-storage,@hookit/interval,@hookit/network-status,@hookit/verification-inputs,@hookit/window-event-listener,@hookit/why-did-you-update,@hookit/sarcasm,@hookit/undo,@hookit/toggle,@hookit/media?interval=7&minimal=true

☝️ Works just fine

https://npmcharts.com/compare/@hookit/doesnt-exist,@hookit/local-storage,@hookit/interval,@hookit/network-status,@hookit/verification-inputs,@hookit/window-event-listener,@hookit/why-did-you-update,@hookit/sarcasm,@hookit/undo,@hookit/toggle,@hookit/media?interval=7&minimal=true

☝Same as above with the addition of `@hookit/doesnt-exist` to the list of packages in the URL. Eventually the server times out with a `504` from cloudflare.

### Suggestion(s)

I think this could fail gracefully by excluding the package that doesn't exist when you make a request for the package details and only showing data for the ones that do exist. You might handle the non-existent package in a couple ways:

* Remove the non-existent package from the URL and redirect
* Keep it in the URL and display it alongside the other packages but striked out with no data. Something like this:

<img width="348" alt="Screen Shot 2020-12-02 at 1 47 03 PM" src="https://user-images.githubusercontent.com/6579532/100917244-e4a17700-34a4-11eb-879b-dce60683c51d.png">

**Comment by cheapsteak** [comment]
Thanks so much for the detailed bug report!  
I've "fixed" it so at least it no longer hangs https://github.com/cheapsteak/npmcharts.com/commit/d03ec6c0587f54300c65bf585f86ebf0ee81a9ef 

I love the idea of crossing out packages that data could not be retrieved for, hoping someone might be able to make that adjustment  

A bit hesitant to use redirects because npm's endpoints do have some occasional stability issues and a link that's broken at any given moment isn't guaranteed to represent missing packages; might be paranoid though, who knows 😄

**Comment by cheapsteak** [comment]
Out of curiosity / ad-hoc user research, where do you share links like this? Slack?

**Comment by devjmetivier** [comment]
@cheapsteak 
> Out of curiosity / ad-hoc user research, where do you share links like this? Slack?

I don't share these frequently in any place in particular. I'm new to these package usage graphs. I just thought it would be fun to add to my [react hooks library I'm building](https://github.com/devjmetivier/hookit). I use Slack and Microsoft Teams frequently for dev work, though, if that's any help.
