### ISSUE TITLE
Show as percentage of [package], with default being lodash

### ISSUE THREAD

**Issue by cheapsteak** [cheapsteak/npmcharts.com#37]
The most popular libraries:  
http://npmcharts.com/compare/lodash,request,async,chalk,express,bluebird,commander,underscore,debug

debug is more depended on by a little bit, but Lodash is universally recognizable

**Comment by JonLim** [comment]
Commenting on this, as it sounds like #102 is similar/duplicated.

What's the desired outcome here? It does sound like desired functionality is:

* When comparing packages, if there is a dependency, determine some sort of percentage of that package's downloads are from the package that depends on it
* Display that percentage somewhere, possibly in the legend?

Let me know if that's off-base, otherwise we can start talking about how the above could be implemented!

**Comment by cheapsteak** [comment]
ack, apologies I think this is another one that needs to be cleaned up  

At the time I was trying to figure out how to account for "ecosystem inflation" (X lib is going up, but is it just keeping up with inflation?) and I was thinking of using "lodash" or "debug" as the measurement for inflation

But I'm no longer sure to what extent that's a useful question to answer, and might not be worth the complexity it'd add to the UX

closing 🙏
